// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangePasswordRequest = {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
};

export type CreateUserRequest = { email: string; password: string };

export type CreateUserResponse = { token: string };

export type ForgottenPasswordRequest = { email: string };

export type ForgottenPasswordResponse = { token: string };

export type LoginRequest = { email: string; password: string };

export type LoginResponse = {
  accessToken: string;
  refreshToken: string;
  iat: number;
  exp: number;
  refreshTokenExp: number;
  refreshTokenIat: number;
};

export type OnboardingRequest = {
  firstName: string;
  lastName: string;
  username: string | null;
  countryIdentifier: string;
};

export type ResendOtpRequest = { flow: string };

export type SetNewPasswordRequest = {
  password: string;
  confirmPassword: string;
};

export type SetNewPasswordResponse = Record<symbol, never>;

export type VerifyAccountRequest = { otp: string };

export type VerifyAccountResponse = { token: string };
