// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcceptInvitationRequest = { token: string };

export type AcceptInvitationResponse = {
  message: string;
  workspace: AcceptedWorkspaceInfo | null;
};

export type AcceptedWorkspaceInfo = {
  identifier: string;
  name: string;
  description: string;
};

export type InviteWorkspaceMemberRequest = {
  email: string;
  firstName: string | null;
  lastName: string | null;
};

export type InviteWorkspaceMemberResponse = {
  invitation_id: string;
  email: string;
  status: string;
};

export type WorkspaceMemberResponse = {
  identifier: string;
  email: string;
  role: string;
  created_at: string;
};
