// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvitationInterface = {
  identifier: string;
  workspaceIdentifier: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  token: string;
  status: string;
  expiresAt: string;
  createdAt: string;
};
