// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OneTimePasswordInterface = {
  identifier: string;
  userIdentifier: string;
  code: string;
  createdAt: string;
  updatedAt: string | null;
};
