// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTtsConfig = {
  userIdentifier: string | null;
  language: string;
  voiceActor: string;
  rate: number;
  pitch: number;
  volume: number;
};

export type UpdateTtsConfig = {
  userIdentifier: string | null;
  language: string;
  voiceActor: string;
  rate: number;
  pitch: number;
  volume: number;
};
