// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsersInterface = {
  identifier: string;
  firstName: string | null;
  lastName: string | null;
  email: string;
  isActive: boolean;
  profilePicture: string | null;
  username: string | null;
  createdAt: string;
  updatedAt: string | null;
  password: string;
};
