// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspacesInterface = {
  name: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  identifier: string;
  isDefault: boolean;
  isHidden: boolean;
  isSecured: boolean;
  passwordHash: string | null;
  userIdentifier: string | null;
};
