// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workspace the authenticated account belongs to, as recorded by its
 * workspace membership row.
 */
export type AccountWorkspaceResponse = {
  identifier: string;
  name: string;
  description: string;
  role: string;
};
