// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWorkspaceProfile = {
  firstName: string;
  lastName: string;
  profilePicture: string | null;
};

export type UpdateWorkspaceProfile = {
  firstName: string | null;
  lastName: string | null;
  profilePicture: string | null;
};
