// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceMembersInterface = {
  identifier: string;
  memberEmail: string;
  role: string;
  userIdentifier: string | null;
  createdAt: string;
  updatedAt: string;
  workspaceIdentifier: string;
};
