words = [
    "Glite",
    "NUXT",
    "TAURI",
    "cdylib",
    "creds",
    "dompurify",
    "getters",
    "lowlight",
    "lucide",
    "moodboard",
    "pinia",
    "rustls",
    "seaography",
    "serde",
    "sqlx",
    "staticlib",
    "vorbis",
]
