[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "migration"

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration-export"
path = "src/bin/export.rs"


[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
hex = "0.4.3"
uuid = { version = "1.21.0", features = ["v4", "js"] }
sea-orm = { version = "2.0.0-rc.37", features = [
    "macros",
    "mock",
    "debug-print",
    "with-uuid",
     "sqlx-postgres",
     "runtime-tokio-rustls",
    "with-chrono",
    "seaography"
] }
tokio = { version = "1.53.1", features = ["macros", "rt"] }
lunar_macros = { version = "0.1.0", path = "../macros" }
substring-replace = "0.2.4"

[dependencies.sea-orm-migration]
version = "~2.0.0-rc.37"
features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",

]
