//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tts_config")]
#[serde(rename_all = "camelCase")]
#[lunar_macros::ts_rs_export_sea_orm_entity_name]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: Uuid,
    pub user_identifier: Option<Uuid>,
    pub language: String,
    pub voice_actor: String,
    #[sea_orm(column_type = "Double")]
    pub rate: f64,
    #[sea_orm(column_type = "Double")]
    pub pitch: f64,
    #[sea_orm(column_type = "Double")]
    pub volume: f64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
