//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspaces")]
#[serde(rename_all = "camelCase")]
#[lunar_macros::ts_rs_export_sea_orm_entity_name]
pub struct Model {
    pub name: String,
    pub description: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: Uuid,
    pub is_default: bool,
    pub is_hidden: bool,
    pub is_secured: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub user_identifier: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bookmark::Entity")]
    Bookmark,
    #[sea_orm(has_many = "super::invitation::Entity")]
    Invitation,
    #[sea_orm(has_many = "super::notes::Entity")]
    Notes,
    #[sea_orm(has_many = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(has_many = "super::recycle_bin::Entity")]
    RecycleBin,
    #[sea_orm(has_many = "super::reminder::Entity")]
    Reminder,
    #[sea_orm(has_many = "super::snippets::Entity")]
    Snippets,
    #[sea_orm(has_many = "super::todo::Entity")]
    Todo,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserIdentifier",
        to = "super::users::Column::Identifier",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::workspace_members::Entity")]
    WorkspaceMembers,
    #[sea_orm(has_many = "super::workspace_profiles::Entity")]
    WorkspaceProfiles,
}

impl Related<super::bookmark::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookmark.def()
    }
}

impl Related<super::invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitation.def()
    }
}

impl Related<super::notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notes.def()
    }
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl Related<super::recycle_bin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecycleBin.def()
    }
}

impl Related<super::reminder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reminder.def()
    }
}

impl Related<super::snippets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Snippets.def()
    }
}

impl Related<super::todo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todo.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::workspace_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceMembers.def()
    }
}

impl Related<super::workspace_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceProfiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::bookmark::Entity")]
    Bookmark,
    #[sea_orm(entity = "super::invitation::Entity")]
    Invitation,
    #[sea_orm(entity = "super::notes::Entity")]
    Notes,
    #[sea_orm(entity = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(entity = "super::recycle_bin::Entity")]
    RecycleBin,
    #[sea_orm(entity = "super::reminder::Entity")]
    Reminder,
    #[sea_orm(entity = "super::snippets::Entity")]
    Snippets,
    #[sea_orm(entity = "super::todo::Entity")]
    Todo,
    #[sea_orm(entity = "super::users::Entity")]
    Users,
    #[sea_orm(entity = "super::workspace_members::Entity")]
    WorkspaceMembers,
    #[sea_orm(entity = "super::workspace_profiles::Entity")]
    WorkspaceProfiles,
}
